### ISSUE TITLE
Integration with DefiLlama

### ISSUE THREAD

**Issue by pmolina** [exactly/protocol#498]
https://docs.llama.fi/list-your-project/submit-a-project

Tasks:
- [x] #525
- [x] #526
- [x] #527
- [x] #540

**Comment by GabrielGruber** [comment]
"All dAPPs that qualify can apply if the teams can provide a publicly-verifiable address (preferably a multi-sig) and a DeFiLlama link to track TVL."

https://polygon.technology/blog/defi-for-all-enters-final-phase-with-15-million-for-polygon-native-dapps

**Comment by pmolina** [comment]
Review this with @GabrielGruber, @cruzdanilo and Fran L.: https://hackmd.io/VQ_21EkUSdSYsTBJJaU-nw?view

**Comment by pmolina** [comment]
Repo here: https://github.com/exactly/DefiLlama-Adapters
