### ISSUE TITLE
[Zapper] Odd borrow rates

### ISSUE THREAD

**Issue by pmolina** [exactly/protocol#535]
On Zapper: https://zapper.fi/apps/exactly?network=ethereum&tab=explore

![Image](https://user-images.githubusercontent.com/599939/210567032-720c198b-3640-4d87-a6ac-495c626f80f4.png)

On Exactly: https://app.exact.ly/

![Image](https://user-images.githubusercontent.com/599939/210567091-0e6172a5-2664-48f5-a5ac-5f8a9499ed45.png)

IMHO the difference between APY and APR shouldn't be so large.

**Comment by cruzdanilo** [comment]
https://github.com/Zapper-fi/studio/pull/2033
